[package]
name = "async-session"
version = "2.0.1"
license = "MIT OR Apache-2.0"
repository = "https://github.com/http-rs/async-session"
documentation = "https://docs.rs/async-session"
description = "Async session support with pluggable middleware"
readme = "README.md"
edition = "2018"
keywords = []
categories = []
authors = [
    "Yoshua Wuyts <yoshuawuyts@gmail.com>"
]

[features]

[dependencies]
async-trait = "0.1.24"
async-std = "1.6.0"
serde = { version = "1.0.114", features = ["rc", "derive"] }
rand = "0.8.3"
base64 = "0.13.0"
sha2 = "0.9.1"
hmac = "0.10.1"
serde_json = "1.0.56"
kv-log-macro = "1.0.7"
bincode = "1.3.1"
chrono = { version = "0.4.13", default-features = false, features = ["clock", "serde", "std"] }
anyhow = "1.0.31"
blake3 = "0.3.5"


[dev-dependencies]
async-std = { version = "1.6.2", features = ["attributes"] }
