[package]
name = "async-session"
version = "3.0.0"
license = "MIT OR Apache-2.0"
repository = "https://github.com/http-rs/async-session"
documentation = "https://docs.rs/async-session"
description = "Async session support with pluggable middleware"
readme = "README.md"
edition = "2018"
keywords = []
categories = []
authors = [
  "Yoshua Wuyts <yoshuawuyts@gmail.com>",
  "Jacob Rothstein <hi@jbr.me>"
]

[dependencies]
async-trait = "0.1.50"
rand = "0.8.3"
base64 = "0.13.0"
sha2 = "0.9.5"
hmac = "0.11.0"
serde_json = "1.0.64"
bincode = "1.3.3"
anyhow = "1.0.40"
blake3 = "1.2.0"
async-lock = "2.4.0"
log = "0.4.14"

[dependencies.serde]
version = "1.0.126"
features = ["rc", "derive"]

[dependencies.chrono]
version = "0.4.19"
default-features = false
features = ["clock", "serde", "std"]

[dev-dependencies.async-std]
version = "1.9.0"
features = ["attributes"]
